### ISSUE TITLE
 Incorrect parameter value for INPUT

### ISSUE THREAD

**Issue by msfine0226** [momaabna/APLS_Plugin#1]
I'm using QGIS 3.26.1 to run the plug in.  It seems to install fine, but when I try to run it I get the following error:

2022-07-20T08:50:16     CRITICAL    Unable to execute algorithm
             Incorrect parameter value for INPUT

2022-07-20T08:50:16     WARNING    Traceback (most recent call last):
              File "C:\Users/mfine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\APLS_Plugin-main\APLS_dialog.py", line 76, in start_apls
              APLS =self.apls(path,path2,processing_folder,file,tol=tol1,sn_tol=tol2)
              File "C:\Users/mfine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\APLS_Plugin-main\APLS_dialog.py", line 85, in apls
              processing.run("native:polygonfromlayerextent", {'INPUT':path,'ROUND_TO':0,'OUTPUT':path.split('.')[0]+'_extnt.shp'})
              File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\tools\general.py", line 108, in run
              return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
              File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\core\Processing.py", line 168, in runAlgorithm
              raise QgsProcessingException(msg)
             _core.QgsProcessingException: Unable to execute algorithm
             Incorrect parameter value for INPUT

I'm using the paths: C:/APLS/Predicted_shp and C:/APLS/test_shp, and inside each is a single subdirectory (e.g., Test01), and inside those are the following: Test.cpg, Test.dbf, Test.prj, Test.shp, and Test.shx.  The Dijkstra tolerance is set to 0 m, and the snapping tolerance 8 m. The terminal says one file is found, but no output is displayed.

Is this related to a path error or something else?

Any help is appreciated!

**Comment by momaabna** [comment]
Make sure your files are in the same structure shown in the documentation and end with '/'.
in your case 
 C:/APLS/Predicted_shp/ and C:/APLS/test_shp/
both   C:/APLS/Predicted_shp/ and C:/APLS/test_shp/ should contain folders inside each folder there is a file have the same name as the folder .shp.
